split ci jobs by team workflows

diff --git a/.github/workflows/project.yml b/.github/workflows/project.yml
--- a/.github/workflows/project.yml
+++ b/.github/workflows/project.yml
@@ -14,163 +14,38 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  integration:
-    strategy:
-      # when one version fails, say 14, all the other versions are stopped
-      # setting fail-fast to false in an attempt to prevent this from happening
-      fail-fast: false
-      matrix:
-        version: [oldest, maintenance, active, latest]
+  actionlint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: ./.github/actions/node
-        with:
-          version: ${{ matrix.version }}
-      # Disable core dumps since some integration tests intentionally abort and core dump generation takes around 5-10s
-      - uses: ./.github/actions/install
-      - run: sudo sysctl -w kernel.core_pattern='|/bin/false'
-      - run: yarn test:integration
-
-  # We'll run these separately for earlier (i.e. unsupported) versions
-  integration-guardrails:
-    strategy:
-      matrix:
-        version: [14.0.0, 14, 16.0.0, eol, 18.0.0, 18.1.0, 20.0.0, 22.0.0]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: ./.github/actions/node
-        with:
-          version: ${{ matrix.version }}
-      - uses: ./.github/actions/install
-      - run: node node_modules/.bin/mocha --colors --timeout 30000 integration-tests/init.spec.js
-
-  integration-guardrails-unsupported:
-    strategy:
-      matrix:
-        version: ['0.8', '0.10', '0.12', '4', '6', '8', '10', '12']
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: ./.github/actions/node
-        with:
-          version: ${{ matrix.version }}
-      - run: node ./init
-      - run: node ./init
-        env:
-          DD_INJECTION_ENABLED: 'true'
-
-  integration-playwright:
-    strategy:
-      matrix:
-        version: [oldest, latest]
-    runs-on: ubuntu-latest
-    env:
-      DD_SERVICE: dd-trace-js-integration-tests
-      DD_CIVISIBILITY_AGENTLESS_ENABLED: 1
-      DD_API_KEY: ${{ secrets.DD_API_KEY }}
-      OPTIONS_OVERRIDE: 1
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: ./.github/actions/node
-        with:
-          version: ${{ matrix.version }}
-      - uses: ./.github/actions/install
-      # Install system dependencies for playwright
-      - run: npx playwright install-deps
-      - run: yarn test:integration:playwright
-        env:
-          NODE_OPTIONS: '-r ./ci/init'
-
-  integration-ci:
-    strategy:
-      matrix:
-        version: [oldest, latest]
-        framework: [cucumber, selenium, jest, mocha]
-    runs-on: ubuntu-latest
-    env:
-      DD_SERVICE: dd-trace-js-integration-tests
-      DD_CIVISIBILITY_AGENTLESS_ENABLED: 1
-      DD_API_KEY: ${{ secrets.DD_API_KEY }}
-      OPTIONS_OVERRIDE: 1
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: ./.github/actions/node
-        with:
-          version: ${{ matrix.version }}
-      - name: Install Google Chrome
+      - uses: ./.github/actions/node/active-lts
+      # NOTE: Ok this next bit seems unnecessary, right? The problem is that
+      # this repo is currently incompatible with npm, at least with the
+      # devDependencies. While this is intended to be corrected, it hasn't yet,
+      # so the easiest thing to do here is just use a fresh package.json. This
+      # is needed because actionlint runs an `npm install` at the beginning.
+      - name: Clear package.json
         run: |
-          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
-          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
-          if [ $? -ne 0 ]; then echo "Failed to add Google key"; exit 1; fi
-          sudo apt-get update
-          sudo apt-get install -y google-chrome-stable
-          if [ $? -ne 0 ]; then echo "Failed to install Google Chrome"; exit 1; fi
-        if: ${{ matrix.framework == 'selenium' }}
-      - name: Install ChromeDriver
+          rm package.json
+          npm init -y
+      - name: actionlint
+        id: actionlint
+        uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821 # v2.0.0
+        with:
+          matcher: true
+          fail-on-error: true
+          shellcheck: false # TODO should we enable this?
+      - name: actionlint Summary
+        if: ${{ steps.actionlint.outputs.exit-code != 0 }}
         run: |
-          export CHROME_VERSION=$(google-chrome --version)
-          CHROME_DRIVER_DOWNLOAD_URL=$(node --experimental-fetch scripts/get-chrome-driver-download-url.js)
-          wget -q "$CHROME_DRIVER_DOWNLOAD_URL"
-          if [ $? -ne 0 ]; then echo "Failed to download ChromeDriver"; exit 1; fi
-          unzip chromedriver-linux64.zip
-          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
-          sudo chmod +x /usr/bin/chromedriver
-        if: ${{ matrix.framework == 'selenium' }}
-      - uses: ./.github/actions/install
-      - run: yarn test:integration:${{ matrix.framework }}
-        env:
-          NODE_OPTIONS: '-r ./ci/init'
-
-  integration-cypress:
-    strategy:
-      matrix:
-        version: [eol, oldest, latest]
-        # 6.7.0 is the minimum version we support in <=5
-        # 10.2.0 is the minimum version we support in >=6
-        # The logic to decide whether the tests run lives in integration-tests/cypress/cypress.spec.js
-        cypress-version: [6.7.0, 10.2.0, latest]
-        module-type: ['commonJS', 'esm']
-    runs-on: ubuntu-latest
-    env:
-      DD_SERVICE: dd-trace-js-integration-tests
-      DD_CIVISIBILITY_AGENTLESS_ENABLED: 1
-      DD_API_KEY: ${{ secrets.DD_API_KEY }}
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: ./.github/actions/node
-        with:
-          version: ${{ matrix.version }}
-      - uses: ./.github/actions/install
-      - run: yarn config set ignore-engines true
-      - run: yarn test:integration:cypress --ignore-engines
-        env:
-          CYPRESS_VERSION: ${{ matrix.cypress-version }}
-          NODE_OPTIONS: '-r ./ci/init'
-          CYPRESS_MODULE_TYPE: ${{ matrix.module-type }}
-          OPTIONS_OVERRIDE: 1
-
-
-  integration-vitest:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        version: [oldest, latest]
-    env:
-      DD_SERVICE: dd-trace-js-integration-tests
-      DD_CIVISIBILITY_AGENTLESS_ENABLED: 1
-      DD_API_KEY: ${{ secrets.DD_API_KEY }}
-      OPTIONS_OVERRIDE: 1
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: ./.github/actions/node
-        with:
-          version: ${{ matrix.version }}
-      - uses: ./.github/actions/install
-      - run: yarn test:integration:vitest
-        env:
-          NODE_OPTIONS: '-r ./ci/init'
+          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
+          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
+          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
+          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
+          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
+          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
+          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
+          exit ${{ steps.actionlint.outputs.exit-code }}
 
   lint:
     runs-on: ubuntu-latest
@@ -179,6 +54,19 @@ jobs:
       - uses: ./.github/actions/node/active-lts
       - uses: ./.github/actions/install
       - run: yarn lint
+
+  package-size-report:
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: ./.github/actions/node/active-lts
+      - uses: ./.github/actions/install
+      - name: Compute module size tree and report
+        uses: qard/heaviest-objects-in-the-universe@e2af4ff3a88e5fe507bd2de1943b015ba2ddda66 # v1.0.0
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
   typescript:
     runs-on: ubuntu-latest
